#!/usr/bin/env bash
# generate-config.sh - Detect this machine's hardware and generate
# etc/proj-mk-ultra.conf from real values (RAM, CPUs, disks, PCI slots).
# Suspected values are shown; every destructive-relevant answer is confirmed.
#
# Usage: ./generate-config.sh [--write]
#   Without --write: prints the generated config to stdout (dry run).
#   With --write: backs up the existing conf and writes the new one.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF="${SCRIPT_DIR}/../etc/proj-mk-ultra.conf"
MODE="${1:-dry}"
HOST_CARVE_GB="${HOST_CARVE_GB:-16}"

say() { echo "  $*"; }

# --- RAM -> memory carve -------------------------------------------------
total_kb=$(awk '/MemTotal/{print $2}' /proc/meminfo)
total_gb=$(( total_kb / 1048576 ))
phys_gb=$(( (total_gb + 7) / 8 * 8 ))          # round to next 8GB stick boundary
child_gb=$(( phys_gb - HOST_CARVE_GB ))
zone_gb=$(( phys_gb - 12 ))                       # host keeps ~12G non-movable base
child_suggestion=$(( zone_gb - 36 ))              # pool needs ~36G scan slack to dodge pinned pages
movable_line="movablecore=${zone_gb}G"

# --- CPUs -> mask (host keeps 0-3) ---------------------------------------
nproc_count=$(nproc)
if [ "${nproc_count}" -lt 5 ]; then
    echo "ERROR: ${nproc_count} CPUs is below the 5-CPU minimum (host 0-3 + child 1+)."
    exit 1
fi
child_mask=$(printf '0x%X' $(( 0xFFFFFFFF & ~( 0xF ) & ((1 << nproc_count) - 1) )))

# --- root filesystem ------------------------------------------------------
root_fs=$(findmnt -n -o FSTYPE / 2>/dev/null || echo "ext4")
case "${root_fs}" in
    btrfs|ext4|xfs|f2fs) child_leapfrog="false"; child_leapfrog_fs="ext4" ;;
    *) root_fs="ext4" ;;
esac
# Leapfrog pair: if host is btrfs, child candidate is ext4 (and vice versa)
case "${root_fs}" in
    btrfs) child_leapfrog_fs="ext4" ;;
    ext4)  child_leapfrog_fs="btrfs" ;;
    xfs)   child_leapfrog_fs="btrfs" ;;
    *)     child_leapfrog_fs="ext4" ;;
esac

# --- disks: first non-root disk, biggest first ----------------------------
root_device=$(df / | awk 'NR==2{print $1}' | sed 's|^/dev/||' | sed 's/[0-9]*$//')
target_disk=$(lsblk -dno NAME 2>/dev/null | awk -v root="${root_device}" '$1 ~ /^(sd|nvme|mmc)/ && $1 != root {disk=$1; exit} END{if (disk) {sub(/[0-9]+$/, "", disk); print disk}}')

# --- GPU + USB controller PCI slots ---------------------------------------
gpu_slot=$(lspci -nn 2>/dev/null | grep -iE "vga|3d|display" | head -1 | awk '{print $1}')
usb_slot=$(lspci -nn 2>/dev/null | grep -iE "usb" | head -1 | awk '{print $1}')
nic_slot=$(lspci -nn 2>/dev/null | grep -iE "ethernet|network" | head -1 | awk '{print $1}')

# --- distro ---------------------------------------------------------------
distro=$(. /etc/os-release 2>/dev/null && echo "${ID}" || echo "unknown")
case "${distro}" in
    arch|manjaro|endeavouros|garuda) pkg="pacman" ;;
    debian|ubuntu|kali*|linuxmint|pop) pkg="apt" ;;
    fedora|rhel|centos|rocky|alma) pkg="dnf" ;;
    *) pkg="unknown" ;;
esac

echo "Detected hardware:"
say "RAM: ${total_gb}GB visible (physical ~${phys_gb}GB) -> zone ${zone_gb}G, suggested child ${child_suggestion}G, host ~$(( phys_gb - zone_gb ))G base"
say "NOTE: the actual pool ceiling is machine-dependent - run scripts/probe-pool-ceiling.sh at boot to find it before trusting CHILD_MEMORY_SIZE"
say "Boot param required: ${movable_line}"
say "Baseline service: the wizard installs mk-baseline.service (applies the pool at boot, pre-session)"
say "CPUs: ${nproc_count} -> CHILD_CPU_MASK=${child_mask}"
say "Root filesystem: ${root_fs}"
say "Target disk (first non-root): ${target_disk:-NONE FOUND (insert the SD/secondary disk)}"
say "GPU slot: ${gpu_slot:-none} (default passthrough - display handoff)"
say "USB controller slot: ${usb_slot:-none} (append to PASSTHROUGH_PCI_DEVICES for USB-root child deployments)"
say "NIC slot: ${nic_slot:-none} (MUST STAY on host - never pass this)"
say "Distro: ${distro} (${pkg})"

if [ "${MODE}" != "--write" ]; then
    echo
    echo "# Dry run - generated config follows. Re-run with --write to install."
    echo "Re-run with: $(basename "$0") --write"
fi

GENERATED="$(mktemp)"
cat > "${GENERATED}" << EOF
# PROJ-MK-ULTRA Configuration
# Generated by useful-scripts/generate-config.sh on $(date)
# Detected from this machine's hardware. Review before deployment.

# Host Configuration
CORE_HOST_FILESYSTEM="${root_fs}"
SECURITY_LEVEL="basic"

# Leapfrog Filesystem Diversity
CHILD_LEAPFROG_FS_ENABLE="false"
CHILD_LEAPFROG_FS="${child_leapfrog_fs}"
CHILD_LEAPFROG_ALT="xfs"

# Cross-Distro Support
CROSS_DISTRO_ENABLE="false"
CHILD_DISTRO="arch"

# Installation Target
INSTALL_TARGET="secondary-disk"

# Child Kernel Configuration
CHILD_ROOT_SIZE="20G"
CHILD_BOOT_SIZE="512M"
CHILD_DATA_SIZE="100%"

# Child Instance Hardware Assignment
CHILD_CPU_MASK="${child_mask}"
CHILD_MEMORY_SIZE="${child_suggestion}G"
PASSTHROUGH_PCI_DEVICES="${gpu_slot:-01:00.0}"
MOVABLECORE="${zone_gb}G"
SPAWN_KEEP_BOUND="true"
MEMORY_RESERVATION_ACKNOWLEDGED="false"
CHILD_KERNEL_PATH=""
CHILD_INITRD_PATH=""

# Security Settings
MODULE_SIGNING_ENFORCE="true"
IOMMU_VERIFY="true"
CAPABILITY_DROPPING="true"
FILESYSTEM_ISOLATION="true"
NETWORK_ISOLATION="true"

# Detection Settings
BOOT_INTEGRITY_MONITOR="true"
HARDWARE_ISOLATION_MONITOR="true"
SYSFS_ACCESS_MONITOR="true"
MODULE_LOADING_MONITOR="true"
BEHAVIORAL_ANOMALY_DETECTION="true"

# Response Settings
AUTO_DESTROY_ON_DETECTION="true"
PRESERVE_USER_DATA="true"
FORENSIC_LOGGING="true"
RECOVERY_PROCEDURES="true"

# Update Settings
AUTO_UPDATE_MAINSTREAM="false"
AUTO_UPDATE_MULTIKERNEL="false"
AUTO_SYNC_CHILD="false"

# Btrfs Snapshot Settings
BTRFS_SNAPSHOT_ENABLE="false"
BTRFS_SNAPSHOT_KEEP="5"

# Disk Configuration (populated by partition-disk.sh)
TARGET_DISK="${target_disk:-}"
CHILD_BOOT_DEVICE=""
CHILD_ROOT_DEVICE=""
CHILD_DATA_DEVICE=""
EOF

echo
if [ "${MODE}" = "--write" ]; then
    echo -ne "Write ${CONF}? Backs up existing. [y/N]: "
    read -r confirm
    if [ "${confirm}" = "y" ] || [ "${confirm}" = "Y" ]; then
        [ -f "${CONF}" ] && cp "${CONF}" "${CONF}.backup.$(date +%Y%m%d-%H%M%S)"
        mkdir -p "$(dirname "${CONF}")"
        cp "${GENERATED}" "${CONF}"
        say "WROTE: ${CONF}"
        say "Boot param for this machine: ${movable_line}  <- add to the multikernel entry"
        say "Review PASSTHROUGH_PCI_DEVICES: GPU display handoff (${gpu_slot:-01:00.0}); append ${usb_slot:-00:14.0} for USB-root deployments"
    else
        say "Cancelled - config at: ${GENERATED}"
    fi
else
    cat "${GENERATED}"
fi
rm -f "${GENERATED}"
